//! Provisioning resolver. On every cold boot the firmware looks for WiFi
//! credentials + claim code in this priority order:
//!
//!   1. `prov` partition — small 16 KB blob flashed alongside the firmware
//!      with `espflash write-bin 0x12000 prov.bin` (generated by the host
//!      `paperanywhere-provtool` CLI). Migrated into NVS + erased on success.
//!   2. SD card `wifi.conf` (board-gated to those with SD slots).
//!   3. Existing NVS state (post-first-boot path).
//!   4. Captive portal (last-resort interactive fallback — currently a stub).
//!
//! The prov migration is handled inside `FwNvs::try_migrate_prov`; this
//! resolver just orchestrates the priority order + decides which `SetupPath`
//! got us here.

use crate::boards::BoardConfig;
use crate::nvs::FwNvs;

/// In-memory representation of a provisioning blob. Used by the (stubbed)
/// SD-card path so the same shape of data flows through whatever source
/// surfaces it. The flash-partition path doesn't go through this type —
/// `FwNvs::try_migrate_prov` reads + decodes + migrates internally.
#[derive(Debug, Clone)]
pub struct ProvData {
    pub ssid: alloc::string::String,
    pub password: alloc::string::String,
    pub backend_url: Option<alloc::string::String>,
    pub claim_code: Option<alloc::string::String>,
}

#[derive(Debug)]
pub enum SetupPath {
    /// Read a valid prov-partition blob; creds migrated to NVS, partition erased.
    FlashPartition,
    /// Read `wifi.conf` from SD card; creds migrated to NVS.
    SdCard,
    /// NVS already had creds from a previous successful boot.
    AlreadyProvisioned,
    /// Captive portal captured creds interactively.
    CaptivePortal,
    /// No credentials anywhere. Caller renders the claim code and halts.
    NotProvisioned,
}

/// Walk the priority list. Returns the path that ultimately succeeded.
///
/// `nvs` is borrowed `&mut` so we can persist any creds we migrate from the
/// prov partition (or future SD card / captive portal) into it before the
/// runtime starts pulling them back out via `NvsStore::load_*`.
pub fn resolve(board: BoardConfig, nvs: &mut FwNvs) -> SetupPath {
    // Path 1: prov partition. The first time the device boots after a fresh
    // flash, the user has typically flashed a prov.bin alongside the
    // firmware; this migrates the contents in and zeros the prov region.
    if nvs.try_migrate_prov() {
        return SetupPath::FlashPartition;
    }

    // Path 2: SD card. Stub — `read_wifi_conf` returns None today.
    if board.has_sd_card {
        if let Some(_prov) = crate::sd_config::read_wifi_conf() {
            esp_println::println!("provisioning: read SD wifi.conf");
            // TODO: migrate SD card prov into nvs via FwNvs once SD wiring
            // lands. Same shape as the flash-prov path.
            return SetupPath::SdCard;
        }
    }

    // Path 3: NVS already has bootstrap state.
    if nvs.is_provisioned() {
        return SetupPath::AlreadyProvisioned;
    }

    // Path 4: captive portal. Currently a stub that returns Err — the real
    // implementation lands when we wire AP mode + the HTTP setup form.
    if crate::wifi::captive_portal().is_ok() {
        return SetupPath::CaptivePortal;
    }

    SetupPath::NotProvisioned
}
